[tool.black]
line-length = 88
target-version = ['py311']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    .eggs
    | .git
    | .venv
    | .env
    | .pytest_cache
    | build
    | dist
)/
'''
